feat: update photoprism to be a kustomize base with overlay + fixes for integrating letsencrypt-secret-loader easily with kustomize

diff --git a/k8s/apps/letsencrypt-secret-loader/base/letsencrypt-secret-loader-cronjob.yaml b/k8s/apps/letsencrypt-secret-loader/base/letsencrypt-secret-loader-cronjob.yaml
--- a/k8s/apps/letsencrypt-secret-loader/base/letsencrypt-secret-loader-cronjob.yaml
+++ b/k8s/apps/letsencrypt-secret-loader/base/letsencrypt-secret-loader-cronjob.yaml
@@ -2,7 +2,6 @@ apiVersion: batch/v1
 kind: CronJob
 metadata:
   name: letsencrypt-secret-loader
-  namespace: letsencrypt-secret-loader
 spec:
   # daily at 12AM
   schedule: "0 0 * * *"
@@ -15,10 +14,23 @@ spec:
           containers:
             - name: cert-renewal
               image: alpine:3.18
+              env:
+                - name: SECRET_NAMESPACE
+                  valueFrom:
+                    fieldRef:
+                      fieldPath: metadata.namespace
               command:
                 - /bin/sh
                 - -c
                 - |
+                  
+                  if [[ -z "$SECRET_NAMESPACE" ]]; then
+                    echo "ERROR: The SECRET_NAMESPACE environment variable is not specified or has an empty value. Set it to the value of the namespace where you want the secret to be created." >&2
+                    exit 1
+                  fi
+
+                  echo "Creating the secret in SECRET_NAMESPACE '$SECRET_NAMESPACE'."
+
                   # Install kubectl
                   apk add --no-cache curl
                   curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
@@ -31,9 +43,8 @@ spec:
 
                   # Update kubernetes secret value
                   #   Run this command again for each namespace:
-                  SECRET_NAMESPACE=photoprism
                  
-                  # note --dry-run=client + kubectl apply will edit if it already exists.
+                  # note --dry-run=client + kubectl apply will also edit secret if it already exists.
                   kubectl create secret generic cert-activescott-com \
                     --namespace=$SECRET_NAMESPACE \
                     --type=kubernetes.io/tls \
